ALIVE_clustersCiv = [] call ALIVE_fnc_hashCreate;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["488780",[11595.2,6287.37,4.93058]]];
_nodes set [count _nodes, ["284731",[11617.5,6326.24,-3.25531]]];
_nodes set [count _nodes, ["562392",[11464.1,6307.43,-0.0323296]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_0"] call ALIVE_fnc_hashSet;
[_cluster,"center",[11537.8,6313.79]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorYellow"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_0",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["488558",[12201.5,6979.28,-11.2659]]];
_nodes set [count _nodes, ["488559",[12167,6951.3,-2.75363]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_1"] call ALIVE_fnc_hashSet;
[_cluster,"center",[12172.4,6955.76]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorYellow"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_1",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["489091",[12260.3,7426.3,-12.6253]]];
_nodes set [count _nodes, ["188663",[12274.9,7467.62,-2.10078]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_2"] call ALIVE_fnc_hashSet;
[_cluster,"center",[12272.7,7460.77]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorYellow"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_2",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["145685",[10824.8,9610.01,-15.9678]]];
_nodes set [count _nodes, ["145699",[10868.8,9610.18,-2.25673]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_3"] call ALIVE_fnc_hashSet;
[_cluster,"center",[10861.6,9610.04]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorYellow"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_3",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["287910",[12955.4,8659.34,-10.8311]]];
_nodes set [count _nodes, ["488815",[12927.4,8624.92,-2.60738]]];
_nodes set [count _nodes, ["488837",[12945.6,8628.97,0]]];
_nodes set [count _nodes, ["488838",[12959.2,8650.95,0]]];
_nodes set [count _nodes, ["291972",[12962.2,8659.52,0]]];
_nodes set [count _nodes, ["488813",[12993.3,8659.85,-11.1002]]];
_nodes set [count _nodes, ["288075",[12951.6,8674.93,-2.60738]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_4"] call ALIVE_fnc_hashSet;
[_cluster,"center",[12946.5,8650.32]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorYellow"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_4",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["299583",[13639,9324.76,-10.8249]]];
_nodes set [count _nodes, ["121255",[13641.1,9369.12,-2.60738]]];
_nodes set [count _nodes, ["489499",[13650.2,9353.56,0]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_5"] call ALIVE_fnc_hashSet;
[_cluster,"center",[13645.3,9358.25]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorYellow"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_5",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["299503",[14259.7,12304.9,-13.1487]]];
_nodes set [count _nodes, ["299536",[14229.5,12272.6,-2.40419]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_6"] call ALIVE_fnc_hashSet;
[_cluster,"center",[14234.3,12277.8]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorYellow"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_6",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["474167",[8514.74,7996.98,0.0240631]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_7"] call ALIVE_fnc_hashSet;
[_cluster,"center",[8516.44,7995.15]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_7",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["214",[9617.12,9829.03,0]]];
_nodes set [count _nodes, ["191919",[9738.75,9966.7,-0.226944]]];
_nodes set [count _nodes, ["17",[9567.88,9818.81,2.28653]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_8"] call ALIVE_fnc_hashSet;
[_cluster,"center",[9653.84,9892.54]] call ALIVE_fnc_hashSet;
[_cluster,"size",113.335] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_8",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["3936",[12560.1,8362.11,-0.156902]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_9"] call ALIVE_fnc_hashSet;
[_cluster,"center",[12559.9,8359.62]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_9",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["606829",[13328.6,9055.83,0.349838]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_10"] call ALIVE_fnc_hashSet;
[_cluster,"center",[13327.4,9058.05]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_10",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["109747",[4940.88,15457.6,-0.182766]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_11"] call ALIVE_fnc_hashSet;
[_cluster,"center",[4939.9,15459.9]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_11",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["219162",[12327.2,15031.4,0]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_12"] call ALIVE_fnc_hashSet;
[_cluster,"center",[12327.6,15028.9]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_12",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["3082",[10214.7,9348.09,0.0705261]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_13"] call ALIVE_fnc_hashSet;
[_cluster,"center",[10213.2,9347.6]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_13",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["1933",[12621.4,7490.31,0.129761]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_14"] call ALIVE_fnc_hashSet;
[_cluster,"center",[12620.3,7489.82]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_14",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["418724",[10415.5,9761.01,-0.0189056]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_15"] call ALIVE_fnc_hashSet;
[_cluster,"center",[10414.4,9761.75]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_15",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["274851",[17263.3,14160.1,-0.1]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_16"] call ALIVE_fnc_hashSet;
[_cluster,"center",[17262.5,14160.9]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_16",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["444866",[11068.1,16903.5,-0.0132885]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_17"] call ALIVE_fnc_hashSet;
[_cluster,"center",[11067,16904.2]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_17",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["302306",[19294.4,13879.2,2.28736]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_18"] call ALIVE_fnc_hashSet;
[_cluster,"center",[19294.4,13879.2]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",30] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorOrange"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCiv,"c_18",_cluster] call ALIVE_fnc_hashSet;
ALIVE_clustersCivPower = [] call ALIVE_fnc_hashCreate;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["488780",[11595.2,6287.37,4.93058]]];
_nodes set [count _nodes, ["284731",[11617.5,6326.24,-3.25531]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_0"] call ALIVE_fnc_hashSet;
[_cluster,"center",[11614,6320.51]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorYellow"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivPower,"c_0",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["488558",[12201.5,6979.28,-11.2659]]];
_nodes set [count _nodes, ["488559",[12167,6951.3,-2.75363]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_1"] call ALIVE_fnc_hashSet;
[_cluster,"center",[12172.4,6955.76]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorYellow"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivPower,"c_1",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["489091",[12260.3,7426.3,-12.6253]]];
_nodes set [count _nodes, ["188663",[12274.9,7467.62,-2.10078]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_2"] call ALIVE_fnc_hashSet;
[_cluster,"center",[12272.7,7460.77]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorYellow"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivPower,"c_2",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["145685",[10824.8,9610.01,-15.9678]]];
_nodes set [count _nodes, ["145699",[10868.8,9610.18,-2.25673]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_3"] call ALIVE_fnc_hashSet;
[_cluster,"center",[10861.6,9610.04]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorYellow"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivPower,"c_3",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["287910",[12955.4,8659.34,-10.8311]]];
_nodes set [count _nodes, ["488815",[12927.4,8624.92,-2.60738]]];
_nodes set [count _nodes, ["488837",[12945.6,8628.97,0]]];
_nodes set [count _nodes, ["488838",[12959.2,8650.95,0]]];
_nodes set [count _nodes, ["291972",[12962.2,8659.52,0]]];
_nodes set [count _nodes, ["488813",[12993.3,8659.85,-11.1002]]];
_nodes set [count _nodes, ["288075",[12951.6,8674.93,-2.60738]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_4"] call ALIVE_fnc_hashSet;
[_cluster,"center",[12946.5,8650.32]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorYellow"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivPower,"c_4",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["299583",[13639,9324.76,-10.8249]]];
_nodes set [count _nodes, ["121255",[13641.1,9369.12,-2.60738]]];
_nodes set [count _nodes, ["489499",[13650.2,9353.56,0]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_5"] call ALIVE_fnc_hashSet;
[_cluster,"center",[13645.3,9358.25]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorYellow"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivPower,"c_5",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["299503",[14259.7,12304.9,-13.1487]]];
_nodes set [count _nodes, ["299536",[14229.5,12272.6,-2.40419]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_6"] call ALIVE_fnc_hashSet;
[_cluster,"center",[14234.3,12277.8]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorYellow"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivPower,"c_6",_cluster] call ALIVE_fnc_hashSet;
ALIVE_clustersCivComms = [] call ALIVE_fnc_hashCreate;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["474167",[8514.74,7996.98,0.0240631]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_0"] call ALIVE_fnc_hashSet;
[_cluster,"center",[8516.44,7995.15]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivComms,"c_0",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["214",[9617.12,9829.03,0]]];
_nodes set [count _nodes, ["191919",[9738.75,9966.7,-0.226944]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_1"] call ALIVE_fnc_hashSet;
[_cluster,"center",[9678.62,9896.41]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivComms,"c_1",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["562392",[11464.1,6307.43,-0.0323296]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_2"] call ALIVE_fnc_hashSet;
[_cluster,"center",[11461.6,6307.07]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivComms,"c_2",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["3936",[12560.1,8362.11,-0.156902]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_3"] call ALIVE_fnc_hashSet;
[_cluster,"center",[12559.9,8359.62]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivComms,"c_3",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["606829",[13328.6,9055.83,0.349838]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_4"] call ALIVE_fnc_hashSet;
[_cluster,"center",[13327.4,9058.05]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivComms,"c_4",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["109747",[4940.88,15457.6,-0.182766]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_5"] call ALIVE_fnc_hashSet;
[_cluster,"center",[4939.9,15459.9]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivComms,"c_5",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["219162",[12327.2,15031.4,0]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_6"] call ALIVE_fnc_hashSet;
[_cluster,"center",[12327.6,15028.9]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivComms,"c_6",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["3082",[10214.7,9348.09,0.0705261]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_7"] call ALIVE_fnc_hashSet;
[_cluster,"center",[10213.2,9347.6]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivComms,"c_7",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["1933",[12621.4,7490.31,0.129761]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_8"] call ALIVE_fnc_hashSet;
[_cluster,"center",[12620.3,7489.82]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivComms,"c_8",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["418724",[10415.5,9761.01,-0.0189056]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_9"] call ALIVE_fnc_hashSet;
[_cluster,"center",[10414.4,9761.75]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivComms,"c_9",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["274851",[17263.3,14160.1,-0.1]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_10"] call ALIVE_fnc_hashSet;
[_cluster,"center",[17262.5,14160.9]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivComms,"c_10",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["444866",[11068.1,16903.5,-0.0132885]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_11"] call ALIVE_fnc_hashSet;
[_cluster,"center",[11067,16904.2]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",40] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorWhite"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivComms,"c_11",_cluster] call ALIVE_fnc_hashSet;
ALIVE_clustersCivFuel = [] call ALIVE_fnc_hashCreate;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["17",[9567.88,9818.81,2.28653]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_0"] call ALIVE_fnc_hashSet;
[_cluster,"center",[9567.88,9818.81]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",30] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorOrange"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivFuel,"c_0",_cluster] call ALIVE_fnc_hashSet;
_cluster = [nil, "create"] call ALIVE_fnc_cluster;
_nodes = [];
_nodes set [count _nodes, ["302306",[19294.4,13879.2,2.28736]]];
[_cluster,"nodes",_nodes] call ALIVE_fnc_hashSet;
[_cluster, "state", _cluster] call ALIVE_fnc_cluster;
[_cluster,"clusterID","c_1"] call ALIVE_fnc_hashSet;
[_cluster,"center",[19294.4,13879.2]] call ALIVE_fnc_hashSet;
[_cluster,"size",100] call ALIVE_fnc_hashSet;
[_cluster,"type","CIV"] call ALIVE_fnc_hashSet;
[_cluster,"priority",30] call ALIVE_fnc_hashSet;
[_cluster,"debugColor","ColorOrange"] call ALIVE_fnc_hashSet;
[ALIVE_clustersCivFuel,"c_1",_cluster] call ALIVE_fnc_hashSet;

ALIVE_clustersCivSettlement = [] call ALIVE_fnc_hashCreate;

ALIVE_clustersCivHQ = [] call ALIVE_fnc_hashCreate;

ALIVE_clustersCivMarine = [] call ALIVE_fnc_hashCreate;

ALIVE_clustersCivConstruction = [] call ALIVE_fnc_hashCreate;
