dir = "@ALIVE";
name = "ArmA 3: ALiVE";
picture = "x\alive\addons\main\logo_alive.paa";
actionName = "$STR_MOD_LAUNCHER_ACTION";
action = "http://alivemod.com";
description = "Bugtracker: https://dev-heaven.net/projects/alive/issues<br/>Documentation: https://dev-heaven.net/projects/alive/documents";
logo = "x\alive\addons\main\logo_alive.pa";
logoOver = "x\alive\addons\main\logo_alive.pa";
tooltip = "Advanced Light Infantry Virtual Environment (ALiVE)";
tooltipOwned = "Advanced Light Infantry Virtual Environment (ALiVE) Owned";
overview = "ALIVE is the next generation dynamic persistent mission Mod for ArmA3. Developed by Arma community veterans, the easy to use modular mission framework provides everything that players and mission makers need to set up and run realistic military operations in almost any scenario up to Company level, including command, combat support, service support and logistics.";
author = "ALiVE Mod Team";
overviewPicture = "x\alive\addons\main\logo_alive.pa";
overviewText = "Advanced Light Infantry Virtual Environment (ALiVE) overviewText";
overviewFootnote = "<br /><br /><t color='#999999'>This content is under Attribution-NonCommercial-NoDerivs 3.0 Unported License.<br />Press <t /><t color='#19d3ff'>Left Shift + P<t /><t color='#999999'> to open the store page for more information.<t />";