class cfgFunctions {
        class PREFIX {
                class COMPONENT {
                        class HAC {description = "The main class"; file = "\x\alive\addons\sys_HAC\fnc_HAC.sqf";recompile = RECOMPILE;};
                        class HAC_Init {description = "The module initialisation function"; file = "\x\alive\addons\sys_HAC\fnc_HAC_Init.sqf";recompile = RECOMPILE;};
						class HAC_AddTask {description = "HAC Add Task"; file = "\x\alive\addons\sys_HAC\functions\HAC_AddTask.sqf";recompile = RECOMPILE;};
						class HAC_AIChatter {description = "HAC AI Chatter"; file = "\x\alive\addons\sys_HAC\functions\HAC_AIChatter.sqf";recompile = RECOMPILE;};
						class HAC_AmmoCount {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_AmmoCount.sqf";recompile = RECOMPILE;};
						class HAC_AmmoDrop {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_AmmoDrop.sqf";recompile = RECOMPILE;};
						class HAC_AngTowards {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_AngTowards.sqf";recompile = RECOMPILE;};
						class HAC_ArtyMission {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_ArtyMission.sqf";recompile = RECOMPILE;};
						class HAC_ArtyPrep {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_ArtyPrep.sqf";recompile = RECOMPILE;};
						class HAC_BBArrRefresh {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_BBArrRefresh.sqf";recompile = RECOMPILE;};
						class HAC_BBSimpleD {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_BBSimpleD.sqf";recompile = RECOMPILE;};
						class HAC_CFF {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_CFF.sqf";recompile = RECOMPILE;};
						class HAC_CFF_FFE {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_CFF_FFE.sqf";recompile = RECOMPILE;};
						class HAC_CFF_TGT {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_CFF_TGT.sqf";recompile = RECOMPILE;};
						class HAC_CloseEnemy {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_CloseEnemy.sqf";recompile = RECOMPILE;};
						class HAC_CloseEnemyB {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_CloseEnemyB.sqf";recompile = RECOMPILE;};
						class HAC_Cluster {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Cluster.sqf";recompile = RECOMPILE;};
						class HAC_ClusterA {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_ClusterA.sqf";recompile = RECOMPILE;};
						class HAC_ClusterB {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_ClusterB.sqf";recompile = RECOMPILE;};
						class HAC_DbgMon {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_DbgMon.sqf";recompile = RECOMPILE;};
						class HAC_Dispatcher {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Dispatcher.sqf";recompile = RECOMPILE;};
						class HAC_DistOrd {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_DistOrd.sqf";recompile = RECOMPILE;};
						class HAC_DistOrdB {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_DistOrdB.sqf";recompile = RECOMPILE;};
						class HAC_ExecutePath {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_ExecutePath.sqf";recompile = RECOMPILE;};
						class HAC_FindBiggest {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_FindBiggest.sqf";recompile = RECOMPILE;};
						class HAC_FindHighestWithIndex {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_FindHighestWithIndex.sqf";recompile = RECOMPILE;};
						class HAC_FindOverwatchPos {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_FindOverwatchPos.sqf";recompile = RECOMPILE;};
						class HAC_FireCount {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_FireCount.sqf";recompile = RECOMPILE;};
						class HAC_Flares {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Flares.sqf";recompile = RECOMPILE;};
						class HAC_FlatLandNoRoad {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_FlatLandNoRoad.sqf";recompile = RECOMPILE;};
						class HAC_ForceAnalyze {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_ForceAnalyze.sqf";recompile = RECOMPILE;};
						class HAC_ForceCount {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_ForceCount.sqf";recompile = RECOMPILE;};
						class HAC_GarrP {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GarrP.sqf";recompile = RECOMPILE;};
						class HAC_GarrS {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GarrS.sqf";recompile = RECOMPILE;};
						class HAC_GoInside {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoInside.sqf";recompile = RECOMPILE;};
						class HAC_GoLaunch {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoLaunch.sqf";recompile = RECOMPILE;};
						class HAC_isNight {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_isNight.sqf";recompile = RECOMPILE;};
						class HAC_isOnMap {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_isOnMap.sqf";recompile = RECOMPILE;};
						class HAC_Itinerary {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Itinerary.sqf";recompile = RECOMPILE;};
						class HAC_KeepAlt {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_KeepAlt.sqf";recompile = RECOMPILE;};
						class HAC_LocLineTransform {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_LocLineTransform.sqf";recompile = RECOMPILE;};
						class HAC_LocMultiTransform {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_LocMultiTransform.sqf";recompile = RECOMPILE;};
						class HAC_LZ {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_LZ.sqf";recompile = RECOMPILE;};
						class HAC_Mark {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Mark.sqf";recompile = RECOMPILE;};
						class HAC_Marker {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Marker.sqf";recompile = RECOMPILE;};
						class HAC_NearestRoad {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_NearestRoad.sqf";recompile = RECOMPILE;};
						class HAC_ObjectivesMon {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_ObjectivesMon.sqf";recompile = RECOMPILE;};
						class HAC_ObjMark {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_ObjMark.sqf";recompile = RECOMPILE;};
						class HAC_PointToSecDst {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_PointToSecDst.sqf";recompile = RECOMPILE;};
						class HAC_PosTowards2D {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_PosTowards2D.sqf";recompile = RECOMPILE;};
						class HAC_RandomAround {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_RandomAround.sqf";recompile = RECOMPILE;};
						class HAC_RandomAroundB {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_RandomAroundB.sqf";recompile = RECOMPILE;};
						class HAC_RandomOrd {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_RandomOrd.sqf";recompile = RECOMPILE;};
						class HAC_Recon {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Recon.sqf";recompile = RECOMPILE;};
						class HAC_ReserveExecuting {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_ReserveExecuting.sqf";recompile = RECOMPILE;};
						class HAC_ResetAI {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_ResetAI.sqf";recompile = RECOMPILE;};
						class HAC_Sectorize {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Sectorize.sqf";recompile = RECOMPILE;};
						class HAC_SizeOrd {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_SizeOrd.sqf";recompile = RECOMPILE;};
						class HAC_Smoke {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Smoke.sqf";recompile = RECOMPILE;};
						class HAC_TerraCognita {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_TerraCognita.sqf";recompile = RECOMPILE;};
						class HAC_TimeMachine {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_TimeMachine.sqf";recompile = RECOMPILE;};
						class HAC_TopoAnalize {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_TopoAnalize.sqf";recompile = RECOMPILE;};
						class HAC_ValueOrd {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_ValueOrd.sqf";recompile = RECOMPILE;};
						class HAC_VarReductor {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_VarReductor.sqf";recompile = RECOMPILE;};
						class HAC_Wait {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Wait.sqf";recompile = RECOMPILE;};
						class HAC_WhereIs {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_WhereIs.sqf";recompile = RECOMPILE;};
						class HAC_WPadd {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_WPadd.sqf";recompile = RECOMPILE;};
						class HAC_WPdel {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_WPdel.sqf";recompile = RECOMPILE;};
						class HAC_WPSync {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_WPSync.sqf";recompile = RECOMPILE;};
						class HAC_MapCenter {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_MapCenter.sqf";recompile = RECOMPILE;};
						class HAC_VoiceComm {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_VoiceComm.sqf";recompile = RECOMPILE;};
						class HAC_Desperado {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Desperado.sqf";recompile = RECOMPILE;};
						class HAC_Front {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Front.sqf";recompile = RECOMPILE;};
						class HAC_EnemyScan {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_EnemyScan.sqf"; recompile = RECOMPILE;};
						class HAC_Flanking {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Flanking.sqf"; recompile = RECOMPILE;};
						class HAC_Garrison {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Garrison.sqf"; recompile = RECOMPILE;};
						class HAC_GoAmmoSupp {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoAmmoSupp.sqf"; recompile = RECOMPILE;};
						class HAC_GoAttAir {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoAttAir.sqf"; recompile = RECOMPILE;};
						class HAC_GoAttArmor {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoAttArmor.sqf"; recompile = RECOMPILE;};
						class HAC_GoAttInf {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoAttInf.sqf"; recompile = RECOMPILE;};
						class HAC_GoAttSniper {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoAttSniper.sqf"; recompile = RECOMPILE;};
						class HAC_GoCapture {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoCapture.sqf"; recompile = RECOMPILE;};
						class HAC_GoDef {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoDef.sqf"; recompile = RECOMPILE;};
						class HAC_GoDefAir {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoDefAir.sqf"; recompile = RECOMPILE;};
						class HAC_GoDefRecon {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoDefRecon.sqf"; recompile = RECOMPILE;};
						class HAC_GoDefRes {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoDefRes.sqf"; recompile = RECOMPILE;};
						class HAC_GoFlank {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoFlank.sqf"; recompile = RECOMPILE;};
						class HAC_GoFuelSupp {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoFuelSupp.sqf"; recompile = RECOMPILE;};
						class HAC_GoIdle {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoIdle.sqf"; recompile = RECOMPILE;};
						class HAC_GoMedSupp {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoMedSupp.sqf"; recompile = RECOMPILE;};
						class HAC_GoRecon {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoRecon.sqf"; recompile = RECOMPILE;};
						class HAC_GoRepSupp {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoRepSupp.sqf"; recompile = RECOMPILE;};
						class HAC_GoRest {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoRest.sqf"; recompile = RECOMPILE;};
						class HAC_GoSFAttack {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_GoSFAttack.sqf"; recompile = RECOMPILE;};
						class HAC_HQOrders {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_HQOrders.sqf"; recompile = RECOMPILE;};
						class HAC_HQOrdersDef {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_HQOrdersDef.sqf"; recompile = RECOMPILE;};
						class HAC_HQReset {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_HQReset.sqf"; recompile = RECOMPILE;};
						class HAC_HQSitRep {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_HQSitRep.sqf"; recompile = RECOMPILE;};
						class HAC_LHQ {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_LHQ.sqf"; recompile = RECOMPILE;};
						class HAC_LPos {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_LPos.sqf"; recompile = RECOMPILE;};
						class HAC_Personality {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Personality.sqf"; recompile = RECOMPILE;};
						class HAC_Reloc {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Reloc.sqf"; recompile = RECOMPILE;};
						class HAC_Rev {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_Rev.sqf"; recompile = RECOMPILE;};
						class HAC_SCargo {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_SCargo.sqf"; recompile = RECOMPILE;};
						class HAC_SFIdleOrd {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_SFIdleOrd.sqf"; recompile = RECOMPILE;};
						class HAC_Spotscan {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_SpotScan.sqf"; recompile = RECOMPILE;};
						class HAC_SuppAmmo {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_SuppAmmo.sqf"; recompile = RECOMPILE;};
						class HAC_SuppFuel {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_SuppFuel.sqf"; recompile = RECOMPILE;};
						class HAC_SuppMed {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_SuppMed.sqf"; recompile = RECOMPILE;};
						class HAC_SuppRep {description = "to be delivered"; file = "\x\alive\addons\sys_HAC\functions\HAC_SuppRep.sqf"; recompile = RECOMPILE;};
						class HAC_OPCOM {description = "OPCOM Controller"; file = "\x\alive\addons\sys_HAC\functions\HAC_OPCOM.sqf"; recompile = RECOMPILE;};
                };
        };
};
