// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------

#include "script_macros_core.hpp"

#define TESTS ["server","client"]

SCRIPT(test-hashes);

// ----------------------------------------------------------------------------

LOG("=== Testing CQB ===");

{
	call compile preprocessFileLineNumbers format ["Enemy\modules\MSO_CQBPOP\test_%1.sqf", _x];
} forEach TESTS;

nil;
